awards = {
   "Best Motion Picture Drama": {"Nominee Type": "Movie", "Nominees":["Argo", "Django Unchained","Life of Pi","Lincoln","Zero Dark Thirty"],"Winner":"Argo"},
   "Best Motion Picture Comedy or Musical" :{"Nominee Type": "Movie","Nominees":["Les Miserables", "Moonrise Kingdom","Salmon Fishing in the Yemen","Silver Linings Playbook","The Best Exotic Marigold Hotel"],"Winner":"Les Miserables"},
   "Best Performance by an Actor in a Motion Picture Drama" :{"Nominee Type": "Person","Nominees":["Daniel Day-Lewis", "Denzel Washington","Joaquin Phoenix","John Hawkes","Richard Gere"],"Winner":"Daniel Day-Lewis"},
   "Best Performance by an Actress in a Motion Picture Drama" :{"Nominee Type": "Person","Nominees":["Jessica Chastain", "Helen Mirren","Marion Cotillard","Naomi Watts","Rachel Weisz"],"Winner":"Jessica Chastain"},
   "Best Performance by an Actor in a Motion Picture Comedy or Musical" :{"Nominee Type": "Person","Nominees":["Hugh Jackman", "Bill Murray","Bradley Cooper","Ewan McGregor","Jack Black"],"Winner":"Hugh Jackman"},
   "Best Performance by an Actress in a Motion Picture Comedy or Musical" :{"Nominee Type": "Person","Nominees":["Jennifer Lawrence", "Emily Blunt","Judi Dench","Maggie Smith","Meryl Streep"],"Winner":"Jennifer Lawrence"},
   "Best Performance by an Actor in a Supporting Role in a Motion Picture" :{"Nominee Type": "Person","Nominees":["Christoph Waltz", "Alan Arkin","Leonardo DiCaprio","Philip Seymour Hoffman","Tommy Lee Jones"],"Winner":"Christoph Waltz"},
   "Best Performance by an Actress in a Supporting Role in a Motion Picture" :{"Nominee Type": "Person","Nominees":["Anne Hathaway", "Amy Adams","Helen Hunt","Nicole Kidman","Sally Field"],"Winner":"Anne Hathaway"},
   "Best Director Motion Picture" :{"Nominee Type": "Person","Nominees":["Ben Affleck", "Ang lee","Kathryn Bigelow","Quentin Tarantino","Steven Spielberg"],"Winner":"Ben Affleck"},
   "Best Screenplay Motion Picture" :{"Nominee Type": "Movie","Nominees":["Django Unchained", "Argo","Lincoln","Silver Linings Playbook","Zero Dark Thirty"],"Winner":"Django Unchained"},
   "Best Original Song Motion Picture" :{"Nominee Type": "Movie","Nominees":["Skyfall", "Act of Valor","Les Miserables","Stand Up Guys","The Hunger Games"],"Winner":"Skyfall"},
   "Best Original Score Picture" :{"Nominee Type": "Movie","Nominees":["Life of Pi", "Anna Karenina","Argo","Cloud Atlas","Lincoln"],"Winner":"Life of Pi"},
   "Best Television Series Drama" :{"Nominee Type": "Show","Nominees":["Homeland", "Boardwalk Empire","Breaking Bad","Downton Abbey","The Newsroom"],"Winner":"Homeland"},
   "Best Television Series Comedy or Musical" :{"Nominee Type": "Show","Nominees":["Girls", "Episodes","Modern Family","Smash","The Big Bang Theory"],"Winner":"Girls"},
   "Best Performance by an Actor in a Television Series Drama" :{"Nominee Type": "Person","Nominees":["Damian Lewis", "Bryan Cranston","Jeff Daniels","Jon Hamm","Steve Buscemi"],"Winner":"Damian Lewis"},
   "Best Performance by an Actress in a Television Series Drama" :{"Nominee Type": "Person","Nominees":["Claire Danes", "Connie Britton","Glenn Close","Julianna Margulies","Michelle Dokcery"],"Winner":"Claire Danes"},
   "Best Performance by an Actor in a Television Series Comedy or Musical" :{"Nominee Type": "Person","Nominees":["Don Cheadle", "Alec Baldwin","Jim Parsons","Louis C.K.","Matt LeBlanc"],"Winner":"Don Cheadle"},
   "Best Performance by an Actress in a Television Series Comedy or Musical" :{"Nominee Type": "Person","Nominees":["Lena Dunham", "Amy Poehler","Julia Louis-Dreyfus","Tina Fey","Zooey Deschanel"],"Winner":"Lena Dunham"},
   "Best Performance by an Actor in a Supporting Role in a Series, Miniseries, or Motion Picture Made for Television" :{"Nominee Type": "Person","Nominees":["Ed Harris", "Danny Huston","Eric Stonestreet","Mandy Patinkin","Max Greenfield"],"Winner":"Ed Harris"},
   "Best Performance by an Actress in a Supporting Role in a Series, Miniseries, or Motion Picture Made for Television" :{"Nominee Type": "Person","Nominees":["Maggie Smith", "Archie Panjabi","Hayden Panettiere","Sarah Paulson","Sofia Vergara"],"Winner":"Maggie Smith"},
   "Best Performance by an Actor in a Miniseries or Motion Picture Made for Television" :{"Nominee Type": "Person","Nominees":["Kevin Costner", "Benedict Cumberbatch","Clive Owen","Toby Jones","Woody Harrelson"],"Winner":"Kevin Costner"},
   "Best Performance by an Actress in a Miniseries or Motion Picture Made for Television" :{"Nominee Type": "Person","Nominees":["Julianne Moore", "Jessica Lange","Nicole Kidman","Sienna Miller","Sigourney Weaver"],"Winner":"Julianne Moore"},
   "Best Animated Feature Film" :{"Nominee Type": "Movie","Nominees":["Brave", "Frankenweenie","Hotel Transylvania","Rise of the Guardians","Wreck-It Ralph"],"Winner":"Brave"},
   "Best Foreign Language Film" :{"Nominee Type": "Movie","Nominees":["Amour", "A Royal Affair","Kon-Tiki","Rust and Bone","The Intouchables"],"Winner":"Amour"},
   "Best Miniseries or Motion Picture Made for Television" :{"Nominee Type": "Show","Nominees":["Game Change", "Hatfields & McCoys","Political Animals","The Girl","The Hour"],"Winner":"Game Change"},
   "Cecil B. DeMille Award" :{"Nominee Type": "Person","Nominees":["Jodie Foster"],"Winner":"Jodie Foster"},
   "Miss Golden Globe" :{"Nominee Type": "Person","Nominees":["Francesca Eastwood"],"Winner":"Francesca Eastwood"},
   "Mr. Golden Globe" :{"Nominee Type": "Person","Nominees":["Sam Fox"],"Winner":"Sam Fox"}

}

people =["Daniel Day-Lewis",
    "Denzel Washington",
    "Joaquin Phoenix",
    "John Hawkes",
    "Richard Gere",
    "Jessica Chastain",
    "Helen Mirren",
    "Marion Cotillard",
    "Naomi Watts",
    "Rachel Weisz",
    "Hugh Jackman",
    "Bill Murray",
    "Bradley Cooper",
    "Ewan McGregor",
    "Jack Black",
    "Jennifer Lawrence",
    "Emily Blunt",
    "Judi Dench",
    "Maggie Smith",
    "Meryl Streep",
    "Christoph Waltz",
    "Alan Arkin",
    "Leonardo DiCaprio",
    "Philip Seymour Hoffman",
    "Tommy Lee Jones",
    "Anne Hathaway",
    "Amy Adams",
    "Helen Hunt",
    "Nicole Kidman",
    "Sally Field",
    "Ben Affleck",
    "Ang lee",
    "Kathryn Bigelow",
    "Quentin Tarantino",
    "Steven Spielberg",
    "Damian Lewis",
    "Bryan Cranston",
    "Jeff Daniels",
    "Jon Hamm",
    "Steve Buscemi",
    "Claire Danes",
    "Connie Britton",
    "Glenn Close",
    "Julianna Margulies",
    "Michelle Dokcery",
    "Don Cheadle",
    "Alec Baldwin",
    "Jim Parsons",
    "Louis C.K.",
    "Matt LeBlanc",
    "Lena Dunham",
    "Amy Poehler",
    "Julia Louis-Dreyfus",
    "Tina Fey",
    "Zooey Deschanel",
    "Ed Harris",
    "Danny Huston",
    "Eric Stonestreet",
    "Mandy Patinkin",
    "Max Greenfield",
    "Maggie Smith",
    "Archie Panjabi",
    "Hayden Panettiere",
    "Sarah Paulson",
    "Sofia Vergara",
    "Kevin Costner",
    "Benedict Cumberbatch",
    "Clive Owen",
    "Toby Jones",
    "Woody Harrelson",
    "Julianne Moore",
    "Jessica Lange",
    "Sienna Miller",
    "Sigourney Weaver",
    "Jodie Foster",
    "Francesca Eastwood",
    "Sam Fox"]

shows = ["Homeland",
    "Boardwalk Empire",
    "Breaking Bad",
    "Downton Abbey",
    "The Newsroom",
    "Girls", 
    "Episodes",
    "Modern Family",
    "Smash",
    "The Big Bang Theory",
    "Game Change",
    "Hatfields & McCoys",
    "Political Animals",
    "The Girl",
    "The Hour"]

movies = ["Argo", 
    "Django Unchained",
    "Life of Pi",
    "Lincoln",
    "Zero Dark Thirty",
    "Les Miserables", 
    "Moonrise Kingdom",
    "Salmon Fishing in the Yemen",
    "Silver Linings Playbook",
    "The Best Exotic Marigold Hotel",
    "Skyfall", 
    "Act of Valor",
    "Stand Up Guys",
    "The Hunger Games",
    "Anna Karenina",
    "Cloud Atlas",
    "Brave",
    "Frankenweenie",
    "Hotel Transylvania",
    "Rise of the Guardians",
    "Wreck-It Ralph",
    "Amour", 
    "A Royal Affair",
    "Kon-Tiki",
    "Rust and Bone",
    "The Intouchables"]